# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite"
  port = 5173
  targetPort = 5173

# Optional: Redirect all requests to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
